apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry-space
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: registry
