apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: postgres
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-rbd-postgresql
  resources:
    requests:
      storage: 10Gi
