---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
data:
  000-default.conf: |
    <IfModule mod_ssl.c>
      <VirtualHost _default_:443>
        ServerName kubecommun.crazedns.ru
        DocumentRoot /var/www/html

        SSLEngine on
        SSLCertificateFile /certs/tls.crt
        SSLCertificateKeyFile /certs/tls.key

        ErrorLog /var/log/apache2/error.log
        CustomLog /var/log/apache2/access.log combined

        <Directory /var/www/html>
          Options FollowSymLinks
          AllowOverride All
          Require all granted
        </Directory>
      </VirtualHost>
    </IfModule>
  apache2.conf: |
    ServerName kubecommun.crazedns.ru
    DefaultRuntimeDir ${APACHE_RUN_DIR}
    PidFile ${APACHE_PID_FILE}
    Timeout 300
    KeepAlive On
    MaxKeepAliveRequests 100
    KeepAliveTimeout 5
    User ${APACHE_RUN_USER}
    Group ${APACHE_RUN_GROUP}
    HostnameLookups Off
    ErrorLog ${APACHE_LOG_DIR}/error.log
    LogLevel warn
    IncludeOptional mods-enabled/*.load
    IncludeOptional mods-enabled/*.conf
    Include ports.conf
    <Directory />
            Options FollowSymLinks
            AllowOverride None
            Require all denied
    </Directory>
    <Directory /usr/share>
            AllowOverride None
            Require all granted
    </Directory>
    <Directory /var/www/>
            Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted
    </Directory>
    AccessFileName .htaccess
    <FilesMatch "^\.ht">
            Require all denied
    </FilesMatch>
    LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
    LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %O" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent
    IncludeOptional conf-enabled/*.conf
    IncludeOptional sites-enabled/*.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
    nodePort: 30443
  selector:
    app: nextcloud
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
type: Opaque
data:
  nextcloud-user: cHJvZF9hZG1fbmM=
  nextcloud-password: WEItQC8yRi51MTc7
  postgres-db: bmNfcHJvZHVjdGlvbg==
  postgres-user: bmNfYXBw
  postgres-password: OTROdSxpIzdPdMKjaA==
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cert
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  secretName: nextcloud-tls
  duration: 2160h
  renewBefore: 360h
  isCA: false
  usages:
  - server auth
  - client auth
  subject:
    organizations:
    - cert-manager
  commonName: kubecommun.crazedns.ru
  dnsNames:
  - kubecommun.crazedns.ru
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
