apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
    nodePort: 30443
  selector:
    app: nextcloud
  externalTrafficPolicy: Local
